### ISSUE TITLE
Downloader cannot find pbzx

### ISSUE THREAD

**Issue by codethought** [rmc-team/macos-downloader#9] opened 2020-01-20 18:43 UTC
The downloader doesn't work trying to create the Mojave installer.. here's the output from the script.

> + Downloaded installer files.
> > Preparing installer.
> ./macOS Downloader.sh: line 354: ./resources/pbzx: No such file or directory
> mv: rename /tmp/Install macOS Mojave/Install macOS Mojave.app to /Users/codethought/Downloads/Mojave/Install macOS Mojave.app: No such file or directory
> mv: rename /tmp/Install macOS Mojave/AppleDiagnostics.chunklist to /Users/codethought/Downloads/Mojave/Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
> mv: rename /tmp/Install macOS Mojave/AppleDiagnostics.dmg to /Users/codethought/Downloads/Mojave/Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
> mv: rename /tmp/Install macOS Mojave/BaseSystem.chunklist to /Users/codethought/Downloads/Mojave/Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
> mv: rename /tmp/Install macOS Mojave/BaseSystem.dmg to /Users/codethought/Downloads/Mojave/Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
> mv: rename /tmp/Install macOS Mojave/InstallESD.dmg to /Users/codethought/Downloads/Mojave/Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
> mv: rename /tmp/Install macOS Mojave/InstallInfo.plist to /Users/codethought/Downloads/Mojave/Install macOS Mojave.app/Contents/Sh+ Prepared installer.
> + Removed temporary files.
> / Thank you for using macOS Downloader.

**Comment by julian-fairfax** [comment] 2020-01-20 19:01
From the output you provided, it seems like the script cannot find the pbzx file in "./resources/pbzx". Are you sure you have the script *and* the resources directory downloaded?

**Comment by codethought** [comment] 2020-01-20 20:30
@julian-fairfax - yessir.. in fact I double-checked that after posting the issue here and re-reading the error output.

**Comment by julian-fairfax** [comment] 2020-01-20 20:33
I’ll look into it but this is a weird issue presentation. Not exactly sure what the cause is.

**Comment by julian-fairfax** [comment] 2020-01-22 19:55
Line 354 simply calls the pbzx binary which is present in the source, the release zip, and my local copy. However, you could try running chmod +x on the pbzx binary as that could be the issue. I'll close this but please let me know if there's anything else I can for you.

**Closed by julian-fairfax** 2020-01-22 19:55 UTC

**Comment by maelcum** [comment] 2020-05-15 11:26
I think it is the previous step that fails. See here: https://github.com/rmc-team/macos-downloader/issues/5#issuecomment-629182006
