### ISSUE TITLE
[BUG] chmod: ./resources/pbzx: No such file or directory

### ISSUE THREAD

**Issue by rmcaninch** [rmc-team/macos-downloader#15] opened 2020-06-17 17:10 UTC
Seems to be the same or similar to other issues mentioned previously. The files appear to download but the installer is not built. And the files from /tmp are gone at the end.

I'm on Mojave 10.14.6 trying to download Mojave Installer.

If I try to fetch the files manually. The URLs appear to work.
http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/BaseSystem.chunklist

iMac:release-155312-230520 user$ sudo ./macOS\ Downloader.sh 
Jun 06 10:50:15 + Checked system environment.
Jun 06 10:50:15 + Root permissions check passed.
Jun 06 10:50:15 + Resources check passed.
Jun 06 10:50:15 + Integrity conectivity check passed.
Jun 06 10:50:17 + Checked system version.
Jun 06 10:50:17 + System support check passed.
Jun 06 10:50:17 / What save folder would you like to use?
Jun 06 10:50:17 / Input a save folder path.
Jun 06 10:50:17 / /Users/user/Downloads/
Jun 06 10:50:36 + Write permissions check passed.
Jun 06 10:50:36 / What operation would you like to run?
Jun 06 10:50:36 / Input an operation number.
Jun 06 10:50:36 /     1 - Catalina
Jun 06 10:50:36 /     2 - Mojave
Jun 06 10:50:36 /     3 - High Sierra
Jun 06 10:50:36 /     4 - Sierra
Jun 06 10:50:36 /     5 - El Capitan
Jun 06 10:50:36 /     6 - Yosemite
Jun 06 10:50:36 / 2
Jun 06 10:50:40 / What operation would you like to run?
Jun 06 10:50:40 / Input an operation number.
Jun 06 10:50:40 /     1 - Installer
Jun 06 10:50:40 / 1
Jun 06 10:50:43 + Downloaded installer files.
Jun 06 11:48:55 > Preparing installer.
chmod: ./resources/pbzx: No such file or directory
./macOS Downloader.sh: line 388: ./resources/pbzx: No such file or directory
mv: rename /tmp/Install macOS Mojave/Install macOS Mojave.app to /Users/user/Downloads/Install macOS Mojave.app: No such file or directory
mv: rename /tmp/Install macOS Mojave/AppleDiagnostics.chunklist to /Users/user/Downloads//Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
mv: rename /tmp/Install macOS Mojave/AppleDiagnostics.dmg to /Users/user/Downloads//Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
mv: rename /tmp/Install macOS Mojave/BaseSystem.chunklist to /Users/user/Downloads//Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
mv: rename /tmp/Install macOS Mojave/BaseSystem.dmg to /Users/user/Downloads//Install macOS Mojave.app/Contents/SharedSupport: No such file or directory
mv: rename /tmp/Install macOS Mojave/InstallESD.dmg to /Users/user/Downloads//Install macOS Mojave.app/Contents/SharedSupport: No + Prepared installer.
Jun 06 11:48:55 + Removed temporary files.
Jun 06 11:48:56 / Thank you for using macOS Downloader.

**Comment by julian-fairfax** [comment] 2020-06-17 18:05
How did you download macOS Downloader? Is the resources folder present in your copy?

**Comment by rmcaninch** [comment] 2020-06-17 18:16
I downloaded the zip file that is under the Releases tab.

The resources folder is there and I can execute the pbzx

**Comment by julian-fairfax** [comment] 2020-06-18 14:57
I'm sorry but I'm not sure what the issue is if the file is there. Maybe try redownloading it?

**Comment by julian-fairfax** [comment] 2020-06-18 16:59
That makes no sense and shouldn't work at all.

**Comment by rmcaninch** [comment] 2020-06-18 17:54
Now that I look back into the Path_Variables() function. Things are going to behave differently depending on whether I execute the script with a relative path or full path.

I've been using a relative path per the Readme file. ./macOS Downloader.sh

The ${0%/*} variable is the parent path. So calling it with a relative path just puts the current directory (.) in $directory_path

Everything else in Prepare_Installer() is using full path names so I'm not seeing what the cd into /tmp is doing for the script.

**Comment by julian-fairfax** [comment] 2020-06-18 17:57
> I'm not seeing what the cd into /tmp is doing for the script.

cpio puts the file in the current folder, that's why we need to cd to the installer download folder

**Comment by rmcaninch** [comment] 2020-06-18 18:23
Oh. When I commented that cd out, I picked current directory for the save directory.

So it built the installer inside my current directory instead of in /tmp I see now the last mv from tmp failed. But in my case I still ended up with an installer.

The executing relative vs full path name is where it is getting mixed up though.

**Comment by julian-fairfax** [comment] 2020-06-19 04:21
This confuses me more than anything but it seems to work for me.

**Comment by rmcaninch** [comment] 2020-06-19 16:01
The current script when I use the verbose flag. I have another PR that appears to work.

sudo /Users/user/Downloads/release-155312-230520/macOS\ Downloader.sh -v
+ Path_Variables
+ script_path='/Users/user/Downloads/release-155312-230520/macOS Downloader.sh'
+ directory_path=/Users/user/Downloads/release-155312-230520
+ resources_path=/Users/user/Downloads/release-155312-230520/resources
+ Check_Environment


sudo ./macOS\ Downloader.sh -v
+ Path_Variables
+ script_path='./macOS Downloader.sh'
+ directory_path=.
+ resources_path=./resources
+ Check_Environment

**Comment by julian-fairfax** [comment] 2020-06-21 05:16
I've tested this and can confirm your issue. I didn't notice it before because I always run it with the full path, and I recommend you do the same.

**Comment by julian-fairfax** [comment] 2020-06-21 11:43
Fixed in [2.4.3](https://github.com/rmc-team/macos-downloader/releases/tag/2.4.3)

**Closed by julian-fairfax** 2020-06-21 11:43 UTC
Labels: bug
